version: '3'
services:
    web:
      image: 'twang2218/gitlab-ce-zh'
      restart: always
      hostname: 'localhost'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://gitlab.hvkcoder.me'
          gitlab_rails['gitlab_shell_ssh_port'] = 2222
          unicorn['port'] = 8888
          nginx['listen_port'] = 80
      ports:
        - '80:80'
        - '443:443'
        - '2222:22'
      volumes:
        - /Users/h-vk/Documents/Project/Kubernetes/docker/gitlab/config:/etc/gitlab
        - /Users/h-vk/Documents/Project/Kubernetes/docker/gitlab/data:/var/opt/gitlab
        - /Users/h-vk/Documents/Project/Kubernetes/docker/gitlab/logs:/var/log/gitlab
