server:
  port: 9010

spring:
  cloud:
    nacos:
      ########################
      # Nacos 服务发现配置
      ########################
      discovery:
        server-addr: 127.0.0.1:8848

########################
# Eureka Client 配置
########################
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka,http://eureka2:8762/eureka