server:
  port: 9000
spring:
  application:
    name: spring-practice
  kafka:
    master:
      bootstrap-servers: k8s-180:9092
      consumer:
        group-id: test-group
        enable-auto-commit: true
    slave:
      bootstrap-servers: k8s-181:9092
      consumer:
        group-id: test-group
        enable-auto-commit: true
  redis:
    host: node-1
    port: 30379
    #    jedis:
    #      pool:
    #        max-active: 8
    #        max-idle: 8
    #        max-wait: 100
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 100
netty:
  host: 127.0.0.1
  port: 9001

scheduler:
  cron: 0/10 * * * * ?
