server:
  port: 9100

spring:
  ########################
  # Spring Security 配置
  ########################
  security:
    ## 设置登录名和密码
    user:
      name: admin
      password: 123456

  ########################
  # Spring 数据库 配置
  ########################
  datasource:
    url: jdbc:mysql://k8s-180:30060/db_security
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  ########################
  # Spring JPA 配置
  ########################
  jpa:
    generate-ddl: true
    show-sql: true
    database: mysql

########################
# Spring Security + CAS 配置
########################
cas:
  ## 验证服务 cas | security
  verifyServer: security
  ## 无授权访问
  notAuthorizeAccess:
    - /login/cas
    - /login
    - /css/**
    - /img/**
    - /captcha.png
  server:
    prefix: http://127.0.0.1:8080/cas
    login: ${cas.server.prefix}/login
    logout: ${cas.server.prefix}/logout
  client:
    prefix: http://localhost:${server.port}
    login: ${cas.client.prefix}/login/cas
    logout-relative: /logout/cas
    logout: ${cas.client.prefix}${cas.client.logout-relative}