version: '3.1'

services:
  zoo1:
    image: zookeeper
    restart: always
    container_name: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      zookeeper:
        ipv4_address: 172.19.0.11
    volumes:
      - $HOME/Docker/zookeeper/zoo1/data:/data
      - $HOME/Docker/zookeeper/zoo1/log:/datalog

  zoo2:
    image: zookeeper
    restart: always
    container_name: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    networks:
      zookeeper:
        ipv4_address: 172.19.0.12
    volumes:
      - $HOME/Docker/zookeeper/zoo2/data:/data
      - $HOME/Docker/zookeeper/zoo2/log:/datalog

  zoo3:
    image: zookeeper
    restart: always
    container_name: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    networks:
      zookeeper:
        ipv4_address: 172.19.0.13
    volumes:
      - $HOME/Docker/zookeeper/zoo3/data:/data
      - $HOME/Docker/zookeeper/zoo3/log:/datalog

networks:
  zookeeper:
    ipam:
      config:
        - subnet: 172.19.0.0/16
