server:
  port: 9010
spring:
  application:
    name: dubbo-consumer
    service:
      version: 1.0.0
########################
# Dubbo 服务配置
########################
dubbo:
  registry:
    address: zookeeper://k8s-180:30181/dubbo