server:
  port: 9000

spring:
  application:
    name: SERVICE-PROVIDER

########################
# Eureka Client 配置
########################
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka,http://eureka2:8762/eureka