apiVersion: v1
kind: Service
metadata:
  name: kafka-hs1
  namespace: development
  labels:
    app: kafka-01
spec:
  selector:
    app: kafka-01
  clusterIP: None
  ports:
  - name: jmx1
    port: 1099
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cs1
  namespace: development
  labels:
    app: kafka-01
spec:
  selector:
    app: kafka-01
  type: NodePort
  ports:
  - name: client1
    port: 9092
    nodePort: 32092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-01
  namespace: development
  labels:
    app: kafka-01
spec:
  replicas: 1
  serviceName: kafka-hs1
  selector:
    matchLabels:
      app: kafka-01
  template:
    metadata:
      labels:
        app: kafka-01
    spec:
      containers:
      - name: kafka-01
        image: hvkcoder/kafka:2.8.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: jmx1
          containerPort: 1099
        - name: client1
          containerPort: 9092
        command: 
        - sh
        - -c
        - "exec bin/kafka-server-start.sh config/server.properties --override broker.id=0 \
           --override advertised.listeners=PLAINTEXT://192.168.56.180:32092 \
           --override zookeeper.connect=zookeeper1.development.svc.cluster.local:2181,zookeeper2.development.svc.cluster.local:2181,zookeeper3.development.svc.cluster.local:2181"
        env:
        - name: KAFKA_HEAP_OPTS
          value : "-Xmx512M -Xms512M"
        - name: KAFKA_OPTS
          value: "-Dlogging.level=INFO"
